apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Values.mysql.common.namespace }}
type: Opaque
data:
{{- range $k, $v := .Values.mysql.secrets}}
  {{ $k }}: {{ $v }}
{{- end }}
