apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.mysql.common.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: {{ .Chart.Name }}
    port: 3306
  clusterIP: None
