mysql:
  common:
    namespace: mysql

  secrets:
    MYSQL_ROOT_PASSWORD: "MTIzNA=="  # Base64 encoding for "1234"
    MYSQL_USER: "YXBwX3VzZXI=" # Base64 encoding for "app_user"
    MYSQL_PASSWORD: "MTIzNA=="  # Base64 encoding for "1234"

  statefulSet:
    replicas: 2

  image:
    repository: mysql
    tag: 8.0

  pvc:
    storage: 2Gi

  tolerations:
    key: "app"
    value: "mysql"

  affinity:
    podaffinity:
      key: "app"
      value:
      - mysql
     nodeaffinity:
      key: "app"
      value:
      - "mysql"

  resources:
    cpu: 256m
    memory: 1Gi
